# Generated by Django 3.2 on 2023-04-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensor_things_board_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='processed',
        ),
    ]
