# Generated by Django 2.2 on 2021-02-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Camera'),
        ),
    ]
