# Generated by Django 3.2 on 2023-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_image_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
