# Generated by Django 3.2 on 2023-04-04 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='confidence_threshold',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
