# Generated by Django 2.2 on 2021-03-08 03:02

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210307_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='color',
            field=models.CharField(default='rgb(75, 192, 192)', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=core.fields.CustomImageField(upload_to='wwf/%Y-%m-%d'),
        ),
    ]
