# Generated by Django 3.2 on 2023-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_camera_confidence_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
