# Generated by Django 2.2 on 2021-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210308_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
