# Generated by Django 3.2 on 2024-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_weather_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nasa_tag',
            field=models.BooleanField(default=False),
        ),
    ]
