# Generated by Django 3.2 on 2024-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_nasa_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='live_stream_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
