# Generated by Django 2.2 on 2021-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_image_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='action',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('REBOOT', 'Reboot'), ('SHUTDOWN', 'Shutdown'), ('TURN_ON', 'Turn On')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='current_status',
            field=models.CharField(blank=True, choices=[('ON', 'On'), ('OFF', 'Off')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='interval',
            field=models.FloatField(default=15),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='power_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='power_on_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='voltage',
            field=models.FloatField(default=0),
        ),
    ]
