# Generated by Django 2.2 on 2021-06-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210628_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='power_off_at',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='power_on_at',
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_on_at', models.DateTimeField(blank=True, null=True)),
                ('power_off_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Camera')),
            ],
        ),
    ]
