# Generated by Django 3.2 on 2024-03-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_camera_live_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTZCameraPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('zoom_min', models.FloatField()),
                ('zoom_max', models.FloatField()),
                ('zoom_default', models.FloatField()),
                ('pan_min', models.FloatField()),
                ('pan_max', models.FloatField()),
                ('pan_default', models.FloatField()),
                ('tilt_min', models.FloatField()),
                ('tilt_max', models.FloatField()),
                ('tilt_default', models.FloatField()),
            ],
        ),
    ]
