# Generated by Django 3.2 on 2024-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ptzcamerapreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptzcamerapreset',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
