# Generated by Django 3.2 on 2024-06-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_weather_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_event_count', models.IntegerField(default=0)),
                ('total_night_event_count', models.IntegerField(default=0)),
                ('total_day_event_count', models.IntegerField(default=0)),
                ('fire_day_event_count', models.IntegerField(default=0)),
                ('smoke_night_event_count', models.IntegerField(default=0)),
                ('fire_night_event_count', models.IntegerField(default=0)),
                ('smoke_day_event_count', models.IntegerField(default=0)),
                ('night_event_with_more_than_one_species', models.IntegerField(default=0)),
                ('day_event_with_more_than_one_species', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.camera')),
            ],
        ),
    ]
