# Generated by Django 2.2 on 2021-07-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_camera_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('file', models.ImageField(upload_to='field/%Y-%m-%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Camera')),
            ],
        ),
    ]
