# Generated by Django 3.2 on 2024-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
