# Generated by Django 2.2 on 2021-07-05 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210705_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='camera',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Camera'),
            preserve_default=False,
        ),
    ]
