# Generated by Django 3.2 on 2025-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20250430_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='contacts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
