# Generated by Django 3.2 on 2025-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_camera_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sms_sent_multiple',
            field=models.TextField(blank=True, null=True),
        ),
    ]
