# Generated by Django 2.2 on 2021-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210802_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='events')),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ManyToManyField(to='core.Specie')),
            ],
        ),
    ]
