# Generated by Django 2.2 on 2021-08-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
