# Generated by Django 2.2 on 2021-12-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Event'),
        ),
    ]
