# Generated by Django 2.2 on 2021-12-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_image_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='event',
        ),
    ]
