# Generated by Django 2.2 on 2021-12-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_image_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Camera'),
        ),
    ]
