# Generated by Django 2.2 on 2021-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_event_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
