# Generated by Django 2.2 on 2022-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_camera_live'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='specie',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
