# Generated by Django 2.2 on 2022-02-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220204_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='camera',
            name='remaining_storage',
            field=models.FloatField(default=64),
        ),
        migrations.AlterField(
            model_name='camera',
            name='update_after',
            field=models.FloatField(default=300),
        ),
    ]
