# Generated by Django 2.2 on 2022-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220207_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='movement_threshold',
            field=models.FloatField(default=1000),
        ),
    ]
