# Generated by Django 2.2 on 2022-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_camera_movement_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='video_interval',
            field=models.IntegerField(default=15),
        ),
    ]
