# Generated by Django 2.2 on 2022-02-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220208_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='frames_per_sec',
            field=models.IntegerField(default=1),
        ),
    ]
