# Generated by Django 2.2 on 2022-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_camera_frames_per_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='movement_threshold',
            new_name='day_threshold',
        ),
        migrations.AddField(
            model_name='camera',
            name='night_threshold',
            field=models.FloatField(default=1000),
        ),
    ]
