# Generated by Django 2.2 on 2022-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220208_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
