# Generated by Django 2.2 on 2022-02-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220223_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='gnd_pin',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='camera',
            name='green_pin',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='camera',
            name='infrared',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='camera',
            name='led_pin',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='camera',
            name='motion_interval',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='camera',
            name='red_pin',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='camera',
            name='yellow_pin',
            field=models.IntegerField(default=18),
        ),
    ]
