# Generated by Django 2.2 on 2022-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220301_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='rest_interval',
            field=models.IntegerField(default=5),
        ),
    ]
