# Generated by Django 2.2 on 2022-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_dontcare'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='iou_threshold',
            field=models.FloatField(default=80),
        ),
    ]
