# Generated by Django 2.2 on 2022-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_camera_iou_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image_height',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='camera',
            name='image_width',
            field=models.IntegerField(default=640),
        ),
    ]
