# Generated by Django 2.2 on 2022-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220301_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='should_log',
            field=models.BooleanField(default=True),
        ),
    ]
