# Generated by Django 2.2 on 2022-03-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220321_1147'),
        ('core', '0038_camera_should_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
        ),
    ]
