# Generated by Django 2.2 on 2022-06-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_demomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
        migrations.AddField(
            model_name='camera',
            name='test',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='FieldImage',
        ),
    ]
