# Generated by Django 2.2 on 2022-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220616_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='led_pin',
        ),
        migrations.AddField(
            model_name='camera',
            name='filter_a',
            field=models.IntegerField(default=16),
        ),
    ]
