# Generated by Django 2.2 on 2022-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20220705_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='gnd_pin',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='green_pin',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='red_pin',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='yellow_pin',
        ),
        migrations.AddField(
            model_name='camera',
            name='filter_b',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='camera',
            name='pwm',
            field=models.IntegerField(default=100),
        ),
    ]
