# Generated by Django 2.2 on 2022-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20220705_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='motion_1',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='camera',
            name='motion_2',
            field=models.IntegerField(default=13),
        ),
    ]
