# Generated by Django 2.2 on 2022-07-06 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20220705_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activity',
            field=models.CharField(choices=[('CAMERA_ERROR', 'CAMERA ERROR'), ('CHECKED_MOTION', 'CHECKED MOTION'), ('EVENT_CAPTURED', 'EVENT CAPTURED')], default='CHECKED_MOTION', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='script',
            field=models.CharField(choices=[('CAPTURE', 'Capture'), ('UPLOAD', 'Upload')], default='CAPTURE', max_length=20),
            preserve_default=False,
        ),
    ]
