# Generated by Django 3.2 on 2022-07-21 17:56

import core.fields
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220706_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=core.fields.CustomImageField(storage=core.storage.OverwriteStorage(), unique=True, upload_to='wwf/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='log',
            name='activity',
            field=models.CharField(choices=[('SMS_FAILED', 'SMS FAILED'), ('ALIVE', 'ALIVE'), ('SCRIPT_STARTED', 'SCRIPT STARTED'), ('CAMERA_ERROR', 'CAMERA ERROR'), ('CHECKED_MOTION', 'CHECKED MOTION'), ('EVENT_CAPTURED', 'EVENT CAPTURED'), ('UPLOAD_SUCCESS', 'UPLOAD SUCCESS'), ('UPLOAD_FAILED', 'UPLOAD FAILED'), ('DETECTOR_FAULT', 'DETECTOR FAULT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='script',
            field=models.CharField(choices=[('CAPTURE', 'Capture'), ('UPLOAD', 'Upload'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
