# Generated by Django 3.2 on 2022-07-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='included',
            field=models.BooleanField(default=True),
        ),
    ]
