# Generated by Django 3.2 on 2022-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_image_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
