# Generated by Django 3.2 on 2022-07-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_image_included'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uuid',
            new_name='event',
        ),
    ]
