# Generated by Django 3.2 on 2022-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
