# Generated by Django 3.2 on 2022-08-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_event_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='contact_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
