# Generated by Django 3.2 on 2022-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20220915_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='action',
        ),
        migrations.AlterField(
            model_name='event',
            name='species',
            field=models.ManyToManyField(null=True, to='core.Specie'),
        ),
    ]
