# Generated by Django 3.2 on 2022-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20220926_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='species',
            field=models.ManyToManyField(blank=True, to='core.Specie'),
        ),
    ]
