# Generated by Django 3.2 on 2022-09-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_event_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='last_captured_at',
        ),
    ]
