# Generated by Django 3.2 on 2022-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_camera_last_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='roi_mask',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
