# Generated by Django 3.2 on 2022-10-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_camera_roi_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='roi_mask',
            field=models.ImageField(blank=True, null=True, upload_to='roi_masks'),
        ),
    ]
