# Generated by Django 3.2 on 2022-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20221102_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('FEATURED', 'Featured'), ('ARCHIVED', 'Archived')], max_length=20, null=True),
        ),
    ]
