# Generated by Django 3.2 on 2022-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20221103_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('FEATURED', 'Featured'), ('ARCHIVED', 'Archived'), ('NONE', 'None')], default=None, max_length=20),
        ),
    ]
