# Generated by Django 3.2 on 2022-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('FEATURED', 'Featured'), ('ARCHIVED', 'Archived'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
