# Generated by Django 3.2 on 2022-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='keep_4g_on',
            field=models.BooleanField(default=True),
        ),
    ]
