# Generated by Django 3.2 on 2023-01-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_camera_keep_4g_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='keep_4g_on',
        ),
    ]
