# Generated by Django 4.1.7 on 2023-02-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tower',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tower',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='Tower',
        ),
    ]
